name = "ax-agent"
description = "Execute AutomatosX agents (same as /ax but alternative name)"
prompt = """
Execute an AutomatosX agent with a specific task.

IMPORTANT: When user types `/ax-agent <agent>, <task>`, you MUST:

1. Split the input on the FIRST comma
2. Extract agent name (text before comma, trimmed)
3. Extract task (text after comma, trimmed)
4. Map display name to agent ID if needed
5. Execute: ax run <agent> "<task>" --provider gemini --timeout 180

AGENT NAME MAPPING (Display Name → Agent ID):
- Bob → backend
- Frank → frontend
- Steve → security
- Queenie → quality
- Oliver → devops
- Daisy → data
- Dana → data-scientist
- Debbee → design
- Wendy → writer
- Paris → product
- Eric → ceo
- Tony → cto
- Rodman → researcher
- Felix → fullstack
- Maya → mobile
- Cynthia → creative-marketer

User Request: {{args}}

Parse the agent and task, then execute the appropriate command.
"""
