name = "ax-clear"
description = "Clear AutomatosX memory or sessions"
prompt = """
Clear AutomatosX memory or session data.

Action: {{args}}

If args mentions "memory" or is empty:
  Execute: ax memory clear

If args mentions "sessions":
  Execute: ax session clear

This will remove stored data to start fresh. Use with caution.

Return the confirmation message.
"""
