name = "ax-memory"
description = "Search and manage AutomatosX agent memory"
prompt = """
Search AutomatosX agent memory.

Query: {{args}}

Execute: ax memory search "{{args}}"

This searches the AutomatosX memory database (SQLite FTS5) for relevant information from past agent interactions.

Return the search results showing:
- Matching memory entries
- Agent that created the memory
- Timestamp
- Relevance score
"""
