name = "ax-status"
description = "Check AutomatosX system status and configuration"
prompt = """
Check the AutomatosX system status.

Execute: ax status

This will show:
- System version and Node.js version
- Project configuration
- Available providers (Claude, Gemini, OpenAI)
- Resource counts (agents, abilities, memory)
- Health status

Return the complete output from the status command.
"""
