name = "ax-update"
description = "Update AutomatosX to the latest version"
prompt = """
Update AutomatosX to the latest version.

Options: {{args}}

If args is empty:
  Execute: ax update
  (Interactive update with confirmation)

If args contains "--check":
  Execute: ax update --check
  (Only check for updates without installing)

If args contains "--yes":
  Execute: ax update --yes
  (Update without confirmation prompt)

This will:
1. Check for the latest version on npm
2. Display changelog from GitHub
3. Ask for confirmation (unless --yes)
4. Install the update globally

Return the complete output from the update process.
"""
