name = "ax-init"
description = "Initialize AutomatosX in a new project"
prompt = """
Initialize AutomatosX in the current or specified directory.

Directory: {{args}}

If args is empty:
  Execute: ax init

If args specifies a directory:
  Execute: ax init {{args}}

This will:
- Create .automatosx directory structure
- Install example agents and abilities
- Setup configuration files
- Configure Claude Code integration (.claude/)
- Configure Gemini CLI integration (.gemini/)
- Initialize git repository
- Update .gitignore

Return the complete initialization output.
"""
