name = "ax-list"
description = "List available AutomatosX agents, abilities, or providers"
prompt = """
List AutomatosX resources.

Task: {{args}}

If args mentions "agents" → Execute: ax list agents
If args mentions "abilities" → Execute: ax list abilities
If args mentions "providers" → Execute: ax list providers
If args is empty → Execute: ax list agents

Return the complete output showing all available resources.
"""
