name: CI

on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'  # Don't run CI on version tags (release workflow handles it)
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript type check
        run: npm run typecheck

      - name: Build project
        run: npm run build

      - name: Run unit tests
        run: npm run test:unit
        timeout-minutes: 15
        env:
          AUTOMATOSX_MOCK_PROVIDERS: 'true'

      - name: Run integration tests
        run: npm run test:integration
        timeout-minutes: 15
        env:
          AUTOMATOSX_MOCK_PROVIDERS: 'true'

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}
          path: coverage/
          retention-days: 7
          if-no-files-found: warn

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript type check
        run: npm run typecheck

      - name: Check build
        run: npm run build
